import type { CaseStudy } from '../../types'

export const caseStudies: CaseStudy[] = [
  {
    id: 'jp-caso-1',
    number: 'Case 01',
    tags: ['ERP integration', 'Industry · Weighbridge', 'Synergy Work'],
    title: 'From the weighbridge reading to the ERP entry, with no manual keying',
    summary:
      'InfoMetal is the application that supervises and tracks the weighbridge process. I designed the whole chain: reading the instrument over the serial port, the web application that shows it in real time, and the integrations that push each operation into Oracle Applications Cloud and bring it back as BI reports.',
    skills: [
      'apex',
      'plsql',
      'oracle',
      'rest',
      'soap',
      'analytics',
      'react',
      'js',
      'socket',
      'node',
      'ts',
      'sql',
    ],
    metaStats: [
      { label: 'Role', value: 'Development Engineer' },
      { label: 'Period', value: '2021 — present' },
      { label: 'Stack', value: 'APEX · React · Express' },
      { label: 'Protocols', value: 'Serial · Socket · REST · SOAP' },
    ],
    problem:
      'The weight is read by an instrument that only speaks over a serial port. Without integration, someone reads the display, copies it onto a spreadsheet, and later another person keys it into the ERP again. Two manual transcriptions per operation, and a single-digit difference only shows up in the closing reconciliation.',
    constraints: [
      'The ERP is SaaS: there is no access to its database, only published services.',
      'The weighbridge cannot be modified or replaced.',
      'The operation cannot stop when the ERP is not responding.',
      'The browser cannot talk to the serial port.',
    ],
    useCaseNote:
      'Who does what and which systems take part. It replaces the screenshots: it describes the functionality without showing any operational data.',
    architectureHeading: 'Architecture and data flow',
    architectureNote: 'Conceptual diagram. Each leg states its protocol and its mode.',
    failureModes: [
      {
        title: 'Failure: port down',
        body: 'The agent retries opening the port and the UI marks the reading as unreliable instead of showing the last known value.',
      },
      {
        title: 'Failure: ERP not responding',
        body: 'The operation is persisted locally and stays queued; the send is retried without blocking the operator.',
      },
      {
        title: 'Failure: duplicate send',
        body: 'A unique business key per operation: resending is idempotent and is recorded in the log.',
      },
    ],
    decisionsHeading: 'Design decisions',
    decisionsTable: [
      {
        decision: 'A local agent with a socket between the weighbridge and the browser',
        discarded: 'A desktop application replacing the web app',
        why: 'The browser cannot reach the serial port. The agent isolates the driver and keeps the UI deployable and updatable without touching the machines on the plant floor.',
      },
      {
        decision: 'A database queue before calling the ERP',
        discarded: 'A synchronous call at the moment of weighing',
        why: 'A SaaS ERP has latency and maintenance windows. The queue gives reprocessing and traceability, and decouples the operation from the availability of the ERP.',
      },
      {
        decision: 'APEX as the integration layer, not as the user interface',
        discarded: 'A separate microservice in Node',
        why: 'The logic lives next to the data in PL/SQL, and APEX already provides deployment, authentication, and service consumption with no extra infrastructure to maintain.',
      },
      {
        decision: 'Reports over a SQL model in Oracle Analytics',
        discarded: 'Exporting to a spreadsheet and charting separately',
        why: 'The model is defined once and every report reads the same definition. No divergent versions of the same metric on different desktops.',
      },
    ],
    implementation: [
      {
        title: 'Service contract towards the ERP',
        code: `POST /erp/integrations/weighing-operations
Content-Type: application/json
Authorization: Bearer <token>

{
  "businessKey":  "OP-DEMO-000148",   -- idempotent key
  "scaleId":      "SCALE_DEMO_01",
  "netWeightKg":  18420.5,
  "capturedAt":   "2026-03-11T09:14:22-05:00",
  "material":     "MAT_DEMO_A",
  "vehiclePlate": "XXX000",
  "source":       "INFOMETAL_AGENT"
}

201 Created  { "erpDocumentId": "DOC-DEMO-77120" }
409 Conflict { "reason": "DUPLICATE_BUSINESS_KEY" }`,
        note: 'The business key is generated by the source, not by the ERP. That makes retrying safe: the second send answers 409 and the queue marks it as already applied instead of duplicating the document.',
      },
      {
        title: 'PL/SQL package for the outbound queue',
        code: `CREATE OR REPLACE PACKAGE pkg_erp_outbox AS

  -- Queues an operation already persisted locally.
  PROCEDURE enqueue (
    p_business_key  IN  VARCHAR2,
    p_payload       IN  CLOB,
    x_queue_id      OUT NUMBER
  );

  -- Takes the pending ones and sends them in a batch.
  -- Retry with growing backoff; the record is never lost.
  PROCEDURE dispatch_pending (
    p_batch_size    IN  NUMBER  DEFAULT 50,
    p_max_attempts  IN  NUMBER  DEFAULT 5
  );

END pkg_erp_outbox;`,
        note: 'Three states in the queue table: PENDING, SENT, FAILED. Whatever exhausts its attempts stays visible on an APEX screen for manual reprocessing, with the ERP error in plain sight.',
      },
      {
        title: 'Reading the serial port and broadcasting to the SPA',
        code: `// Local agent — normalizes the frame and broadcasts it.
port.on('data', (chunk) => {
  const reading = parseFrame(chunk);        // "ST,GS,+018420.5kg"
  if (!reading.stable) return;              // stable weight only
  io.emit('weight', {
    scaleId: 'SCALE_DEMO_01',
    netWeightKg: reading.kg,
    capturedAt: new Date().toISOString()
  });
});

port.on('error', () => io.emit('scale:offline'));`,
        note: 'The weight is broadcast only when the instrument reports a stable reading. The UI distinguishes three states — stable, unstable, and offline — so the operator never records a value that is still moving.',
      },
    ],
    outcome: [
      'The two manual transcriptions per operation are gone.',
      'The weight reaches the ERP with a timestamp and traceability back to the instrument.',
      'Supervision moved from spreadsheets to the InfoMetal Reporteador built on Oracle Analytics.',
      'The plant keeps operating when the ERP does not respond; nothing is lost.',
    ],
    outcomeNote: 'The Reporteador is an internal system of the client; I do not publish its URL.',
    learnings: [
      'That the hard part of integrating with a corporate ERP is not the service call: it is deciding what happens when it fails. Idempotency and the queue are what made the system reliable, not speed.',
      'And that on the plant floor the interface has to be honest about what it does not know. Showing “offline” is better than showing a stale number.',
    ],
  },

  {
    id: 'jp-caso-2',
    number: 'Case 02',
    tags: ['Legacy system', 'Public sector · Education', 'Universidad de la Amazonia'],
    title: 'Maintaining and extending “Chaira”, the academic and administrative system',
    summary:
      'As an administrative technician I worked on a production system that institutional processes depend on, among them the procurement modules. The job was half engineering and half translation: gathering the requirement with the team that runs the process and carrying it into an inherited codebase without breaking what already worked.',
    skills: ['csharp', 'dotnet', 'oracle', 'plsql', 'sql', 'git'],
    metaStats: [
      { label: 'Role', value: 'Administrative technician' },
      { label: 'Period', value: '2021 — 2022' },
      { label: 'Stack', value: 'C# · .NET · Ext.NET' },
      { label: 'Database', value: 'Oracle · PL/SQL' },
    ],
    problem:
      'A system with years of history, layers piled on top of each other, and logic split between the application and the database. Every small change was expensive because nobody knew for certain what else it touched, and the reports the departments asked for were put together by hand outside the system.',
    constraints: [
      'A production system with institutional users every single day.',
      'No rewrites: only maintain, refactor, and extend.',
      'Processes on a fixed calendar — changes land between windows.',
      'Business logic inside Oracle procedures, functions, and types.',
    ],
    useCaseNote: 'The procurement modules from the perspective of the people who use them.',
    architectureHeading: 'Workflow',
    architectureNote:
      'Here the diagram is not about architecture but about process: this is how a requirement came in and how it went out to production.',
    decisionsHeading: 'Criteria I applied',
    criteriaStyle: 'grid',
    criteria: [
      {
        title: 'Refactoring with a scope',
        body: 'I clean up only the path the requirement runs through. A broad refactor in a system without tests is a risk, not an improvement.',
      },
      {
        title: 'The logic stays where the data lives',
        body: 'If the rule is already in an Oracle procedure, I fix it there. Duplicating it in C# creates two truths.',
      },
      {
        title: 'The report, inside the system',
        body: 'Turning into a template what used to be assembled by hand every month. It is what gives the most time back to the department using it.',
      },
    ],
    implementation: [],
    outcome: [
      'New features in production without interrupting institutional operations.',
      'Recurring reports turned into templates of the system.',
      'Code and database objects left more readable for whoever came next.',
    ],
    learnings: [
      'To read code I did not write, and to ask before changing it. In a legacy system the most valuable skill is not writing code fast: it is understanding why something was built that way before deciding that it is wrong.',
    ],
  },

  {
    id: 'jp-caso-3',
    number: 'Case 03',
    tags: ['Research', 'Offline mobile', 'Grupo GIECOM'],
    title: 'Rainforest Community Manager: field capture with no signal',
    summary:
      'A research project of Universidad de la Amazonia. I built the mobile capture application, the local database, the NestJS backend, and its deployment. The requirement that shaped the whole architecture: there is no connectivity in the rainforest, and the data cannot wait until there is.',
    skills: ['nest', 'ts', 'node', 'postgres', 'unity', 'csharp', 'sqlite', 'swagger', 'aws', 'js'],
    metaStats: [
      { label: 'Role', value: 'Software developer' },
      { label: 'Period', value: '2020' },
      { label: 'Mobile client', value: 'Unity · C# · SQLite' },
      { label: 'Backend', value: 'NestJS · TypeORM · PostgreSQL' },
    ],
    useCaseNote:
      'Capture works with no connection; synchronization is a use case of its own, not a side effect.',
    architectureHeading: 'Architecture',
    decisionsHeading: 'Decisions',
    decisionsPlacement: 'finalGrid',
    criteriaStyle: 'list',
    criteria: [
      {
        title: 'SQLite as the primary source in the field, not as a cache',
        body: 'the app works fully without a network and synchronizes when there is one.',
      },
      {
        title: 'An API documented with Swagger from day one',
        body: 'because the team that consumes the data is not the one that writes it.',
      },
      {
        title: 'Unity for the mobile client',
        body: 'taking advantage of the same environment as the interactive component of the project.',
      },
    ],
    implementation: [],
    learnings: [
      'That designing for “offline” forces you to decide up front what happens when two versions of the same record meet. It is the same question that came back to me years later in the outbound queue towards the ERP.',
    ],
  },
]
