import type { TechNote } from '../../types'

// Sección visible por defecto en el prototipo (showNotes: true). El propio
// prototipo aclara: "Estructura lista. Los tres títulos son los temas que
// propongo; el contenido lo escribes tú." — son placeholders intencionales.
export const techNotes: TechNote[] = [
  {
    category: 'Integration',
    title: 'Idempotency in ERP SaaS integrations',
    description: 'Why the business key should be generated by the source, not the destination.',
    status: 'Draft',
  },
  {
    category: 'Oracle APEX',
    title: 'APEX as an integration layer, not an interface',
    description: "A little-discussed use of the tool and when it makes sense.",
    status: 'Draft',
  },
  {
    category: 'Hardware',
    title: 'From serial port to browser without lying to the user',
    description: 'Reading states, and why "offline" beats a stale number.',
    status: 'Draft',
  },
]
